default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5
  username: ubuntu
  password: shimba

development:
  <<: *default
  database: shimba_development

test:
  <<: *default
  database: shimba_test

production:
  <<: *default
  encoding: unicode
  database: shimpa_production